version: '3.9'

services:
  frontend:
    build:
      context: ./FrontCRUD
    ports:
      - "4200:4200"
    depends_on:
      - db

  backend:
    build:
      context: ./NewAPI
    ports:
      - "5095:8080" # Map container port 8080 to host port 5095
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=test1234
      - DB_NAME=Tester1212
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: Tester
    ports:
      - "3306:3306"
    volumes:
      - ./SQL/:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge